# config/packages/knp_gaufrette.yaml
knp_gaufrette:
    adapters:
        userfiles:
            local:
                directory: '%kernel.project_dir%/var/files/users'

        usergroupfiles:
            local:
                directory: '%kernel.project_dir%/var/files/groups'

    filesystems:
        userfiles:
            adapter:    userfiles

        usergroupfiles:
            adapter:    usergroupfiles

    stream_wrapper: ~
