# config/packages/knp_gaufrette.yaml
knp_gaufrette:
    adapters:
        userfiles:
            local:
                directory: '%kernel.project_dir%/var/files/users'

        usergroupfiles:
            local:
                directory: '%kernel.project_dir%/var/files/groups'

        appfiles:
            local:
                directory: '%kernel.project_dir%/public/media/layout'

    filesystems:
        userfiles:
            adapter:    userfiles

        usergroupfiles:
            adapter:    usergroupfiles

        appfiles:
            adapter:    appfiles

    stream_wrapper: ~
