<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230228102130 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE pollinisateurs_articles DROP FOREIGN KEY FK_2BC23EBDF675F31B');
        $this->addSql('ALTER TABLE pollinisateurs_articles DROP FOREIGN KEY FK_2BC23EBD922726E9');
        $this->addSql('ALTER TABLE pollinisateurs_articles DROP FOREIGN KEY FK_2BC23EBDD2112630');
        $this->addSql('DROP INDEX idx_2bc23ebdd2112630 ON pollinisateurs_articles');
        $this->addSql('CREATE INDEX IDX_86653705D2112630 ON pollinisateurs_articles (usergroup_id)');
        $this->addSql('DROP INDEX idx_2bc23ebdf675f31b ON pollinisateurs_articles');
        $this->addSql('CREATE INDEX IDX_86653705F675F31B ON pollinisateurs_articles (author_id)');
        $this->addSql('DROP INDEX uniq_2bc23ebd922726e9 ON pollinisateurs_articles');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_86653705922726E9 ON pollinisateurs_articles (cover_id)');
        $this->addSql('ALTER TABLE pollinisateurs_articles ADD CONSTRAINT FK_2BC23EBDF675F31B FOREIGN KEY (author_id) REFERENCES pollinisateurs_users (id)');
        $this->addSql('ALTER TABLE pollinisateurs_articles ADD CONSTRAINT FK_2BC23EBD922726E9 FOREIGN KEY (cover_id) REFERENCES pollinisateurs_files (id)');
        $this->addSql('ALTER TABLE pollinisateurs_articles ADD CONSTRAINT FK_2BC23EBDD2112630 FOREIGN KEY (usergroup_id) REFERENCES pollinisateurs_usergroups (id)');
        $this->addSql('ALTER TABLE pollinisateurs_discussion DROP FOREIGN KEY FK_AC4941DBD2112630');
        $this->addSql('ALTER TABLE pollinisateurs_discussion DROP FOREIGN KEY FK_AC4941DBF675F31B');
        $this->addSql('DROP INDEX idx_ac4941dbd2112630 ON pollinisateurs_discussion');
        $this->addSql('CREATE INDEX IDX_F9897068D2112630 ON pollinisateurs_discussion (usergroup_id)');
        $this->addSql('DROP INDEX idx_ac4941dbf675f31b ON pollinisateurs_discussion');
        $this->addSql('CREATE INDEX IDX_F9897068F675F31B ON pollinisateurs_discussion (author_id)');
        $this->addSql('ALTER TABLE pollinisateurs_discussion ADD CONSTRAINT FK_AC4941DBD2112630 FOREIGN KEY (usergroup_id) REFERENCES pollinisateurs_usergroups (id)');
        $this->addSql('ALTER TABLE pollinisateurs_discussion ADD CONSTRAINT FK_AC4941DBF675F31B FOREIGN KEY (author_id) REFERENCES pollinisateurs_users (id)');
        $this->addSql('ALTER TABLE pollinisateurs_discussion_message DROP FOREIGN KEY FK_E67EECB6F675F31B');
        $this->addSql('ALTER TABLE pollinisateurs_discussion_message DROP FOREIGN KEY FK_E67EECB61ADED311');
        $this->addSql('DROP INDEX idx_e67eecb61aded311 ON pollinisateurs_discussion_message');
        $this->addSql('CREATE INDEX IDX_5108CD1B1ADED311 ON pollinisateurs_discussion_message (discussion_id)');
        $this->addSql('DROP INDEX idx_e67eecb6f675f31b ON pollinisateurs_discussion_message');
        $this->addSql('CREATE INDEX IDX_5108CD1BF675F31B ON pollinisateurs_discussion_message (author_id)');
        $this->addSql('ALTER TABLE pollinisateurs_discussion_message ADD CONSTRAINT FK_E67EECB6F675F31B FOREIGN KEY (author_id) REFERENCES pollinisateurs_users (id)');
        $this->addSql('ALTER TABLE pollinisateurs_discussion_message ADD CONSTRAINT FK_E67EECB61ADED311 FOREIGN KEY (discussion_id) REFERENCES pollinisateurs_discussion (id)');
        $this->addSql('ALTER TABLE pollinisateurs_discussion_message_file DROP FOREIGN KEY FK_84DF540FD1F18135');
        $this->addSql('ALTER TABLE pollinisateurs_discussion_message_file DROP FOREIGN KEY FK_84DF540F93CB796C');
        $this->addSql('DROP INDEX idx_84df540fd1f18135 ON pollinisateurs_discussion_message_file');
        $this->addSql('CREATE INDEX IDX_EF1EEBEED1F18135 ON pollinisateurs_discussion_message_file (discussion_message_id)');
        $this->addSql('DROP INDEX idx_84df540f93cb796c ON pollinisateurs_discussion_message_file');
        $this->addSql('CREATE INDEX IDX_EF1EEBEE93CB796C ON pollinisateurs_discussion_message_file (file_id)');
        $this->addSql('ALTER TABLE pollinisateurs_discussion_message_file ADD CONSTRAINT FK_84DF540FD1F18135 FOREIGN KEY (discussion_message_id) REFERENCES pollinisateurs_discussion_message (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pollinisateurs_discussion_message_file ADD CONSTRAINT FK_84DF540F93CB796C FOREIGN KEY (file_id) REFERENCES pollinisateurs_files (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pollinisateurs_document DROP FOREIGN KEY FK_4C7685A3A76ED395');
        $this->addSql('ALTER TABLE pollinisateurs_document DROP FOREIGN KEY FK_4C7685A3162CB942');
        $this->addSql('ALTER TABLE pollinisateurs_document DROP FOREIGN KEY FK_4C7685A3D2112630');
        $this->addSql('ALTER TABLE pollinisateurs_document DROP FOREIGN KEY FK_4C7685A393CB796C');
        $this->addSql('DROP INDEX idx_4c7685a3a76ed395 ON pollinisateurs_document');
        $this->addSql('CREATE INDEX IDX_E1D18C1BA76ED395 ON pollinisateurs_document (user_id)');
        $this->addSql('DROP INDEX idx_4c7685a3d2112630 ON pollinisateurs_document');
        $this->addSql('CREATE INDEX IDX_E1D18C1BD2112630 ON pollinisateurs_document (usergroup_id)');
        $this->addSql('DROP INDEX idx_4c7685a393cb796c ON pollinisateurs_document');
        $this->addSql('CREATE INDEX IDX_E1D18C1B93CB796C ON pollinisateurs_document (file_id)');
        $this->addSql('DROP INDEX idx_4c7685a3162cb942 ON pollinisateurs_document');
        $this->addSql('CREATE INDEX IDX_E1D18C1B162CB942 ON pollinisateurs_document (folder_id)');
        $this->addSql('ALTER TABLE pollinisateurs_document ADD CONSTRAINT FK_4C7685A3A76ED395 FOREIGN KEY (user_id) REFERENCES pollinisateurs_users (id)');
        $this->addSql('ALTER TABLE pollinisateurs_document ADD CONSTRAINT FK_4C7685A3162CB942 FOREIGN KEY (folder_id) REFERENCES pollinisateurs_document_folder (id)');
        $this->addSql('ALTER TABLE pollinisateurs_document ADD CONSTRAINT FK_4C7685A3D2112630 FOREIGN KEY (usergroup_id) REFERENCES pollinisateurs_usergroups (id)');
        $this->addSql('ALTER TABLE pollinisateurs_document ADD CONSTRAINT FK_4C7685A393CB796C FOREIGN KEY (file_id) REFERENCES pollinisateurs_files (id)');
        $this->addSql('ALTER TABLE pollinisateurs_document_folder DROP FOREIGN KEY FK_8AFF503CD2112630');
        $this->addSql('DROP INDEX idx_8aff503cd2112630 ON pollinisateurs_document_folder');
        $this->addSql('CREATE INDEX IDX_C36C826DD2112630 ON pollinisateurs_document_folder (usergroup_id)');
        $this->addSql('ALTER TABLE pollinisateurs_document_folder ADD CONSTRAINT FK_8AFF503CD2112630 FOREIGN KEY (usergroup_id) REFERENCES pollinisateurs_usergroups (id)');
        $this->addSql('ALTER TABLE pollinisateurs_files DROP FOREIGN KEY FK_1922520BD2112630');
        $this->addSql('ALTER TABLE pollinisateurs_files DROP FOREIGN KEY FK_1922520BA76ED395');
        $this->addSql('DROP INDEX idx_1922520ba76ed395 ON pollinisateurs_files');
        $this->addSql('CREATE INDEX IDX_E5C5E52BA76ED395 ON pollinisateurs_files (user_id)');
        $this->addSql('DROP INDEX idx_1922520bd2112630 ON pollinisateurs_files');
        $this->addSql('CREATE INDEX IDX_E5C5E52BD2112630 ON pollinisateurs_files (usergroup_id)');
        $this->addSql('ALTER TABLE pollinisateurs_files ADD CONSTRAINT FK_1922520BD2112630 FOREIGN KEY (usergroup_id) REFERENCES pollinisateurs_usergroups (id)');
        $this->addSql('ALTER TABLE pollinisateurs_files ADD CONSTRAINT FK_1922520BA76ED395 FOREIGN KEY (user_id) REFERENCES pollinisateurs_users (id)');
        $this->addSql('ALTER TABLE pollinisateurs_log_events DROP FOREIGN KEY FK_2A8DBC3CA76ED395');
        $this->addSql('ALTER TABLE pollinisateurs_log_events DROP FOREIGN KEY FK_2A8DBC3CD2112630');
        $this->addSql('ALTER TABLE pollinisateurs_log_events CHANGE data data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\'');
        $this->addSql('DROP INDEX idx_2a8dbc3ca76ed395 ON pollinisateurs_log_events');
        $this->addSql('CREATE INDEX IDX_7F4D8D8FA76ED395 ON pollinisateurs_log_events (user_id)');
        $this->addSql('DROP INDEX idx_2a8dbc3cd2112630 ON pollinisateurs_log_events');
        $this->addSql('CREATE INDEX IDX_7F4D8D8FD2112630 ON pollinisateurs_log_events (usergroup_id)');
        $this->addSql('ALTER TABLE pollinisateurs_log_events ADD CONSTRAINT FK_2A8DBC3CA76ED395 FOREIGN KEY (user_id) REFERENCES pollinisateurs_users (id)');
        $this->addSql('ALTER TABLE pollinisateurs_log_events ADD CONSTRAINT FK_2A8DBC3CD2112630 FOREIGN KEY (usergroup_id) REFERENCES pollinisateurs_usergroups (id)');
        $this->addSql('ALTER TABLE pollinisateurs_pages DROP FOREIGN KEY FK_3F63F727D2112630');
        $this->addSql('ALTER TABLE pollinisateurs_pages DROP FOREIGN KEY FK_3F63F727F675F31B');
        $this->addSql('ALTER TABLE pollinisateurs_pages DROP FOREIGN KEY FK_3F63F727922726E9');
        $this->addSql('DROP INDEX idx_3f63f727d2112630 ON pollinisateurs_pages');
        $this->addSql('CREATE INDEX IDX_C3844007D2112630 ON pollinisateurs_pages (usergroup_id)');
        $this->addSql('DROP INDEX idx_3f63f727f675f31b ON pollinisateurs_pages');
        $this->addSql('CREATE INDEX IDX_C3844007F675F31B ON pollinisateurs_pages (author_id)');
        $this->addSql('DROP INDEX uniq_3f63f727922726e9 ON pollinisateurs_pages');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C3844007922726E9 ON pollinisateurs_pages (cover_id)');
        $this->addSql('ALTER TABLE pollinisateurs_pages ADD CONSTRAINT FK_3F63F727D2112630 FOREIGN KEY (usergroup_id) REFERENCES pollinisateurs_usergroups (id)');
        $this->addSql('ALTER TABLE pollinisateurs_pages ADD CONSTRAINT FK_3F63F727F675F31B FOREIGN KEY (author_id) REFERENCES pollinisateurs_users (id)');
        $this->addSql('ALTER TABLE pollinisateurs_pages ADD CONSTRAINT FK_3F63F727922726E9 FOREIGN KEY (cover_id) REFERENCES pollinisateurs_files (id)');
        $this->addSql('ALTER TABLE pollinisateurs_pages_revisions DROP FOREIGN KEY FK_9B744781A76ED395');
        $this->addSql('ALTER TABLE pollinisateurs_pages_revisions DROP FOREIGN KEY FK_9B744781C4663E4');
        $this->addSql('ALTER TABLE pollinisateurs_pages_revisions CHANGE data data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\'');
        $this->addSql('DROP INDEX idx_9b744781c4663e4 ON pollinisateurs_pages_revisions');
        $this->addSql('CREATE INDEX IDX_D2E795D0C4663E4 ON pollinisateurs_pages_revisions (page_id)');
        $this->addSql('DROP INDEX idx_9b744781a76ed395 ON pollinisateurs_pages_revisions');
        $this->addSql('CREATE INDEX IDX_D2E795D0A76ED395 ON pollinisateurs_pages_revisions (user_id)');
        $this->addSql('ALTER TABLE pollinisateurs_pages_revisions ADD CONSTRAINT FK_9B744781A76ED395 FOREIGN KEY (user_id) REFERENCES pollinisateurs_users (id)');
        $this->addSql('ALTER TABLE pollinisateurs_pages_revisions ADD CONSTRAINT FK_9B744781C4663E4 FOREIGN KEY (page_id) REFERENCES pollinisateurs_pages (id)');
        $this->addSql('DROP INDEX uniq_a317b8315e237e06 ON pollinisateurs_sites');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5FF00F115E237E06 ON pollinisateurs_sites (name)');
        $this->addSql('DROP INDEX uniq_504b31ba989d9b62 ON pollinisateurs_skills');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6BD9F6C5989D9B62 ON pollinisateurs_skills (slug)');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups DROP FOREIGN KEY FK_F4679660922726E9');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups DROP FOREIGN KEY FK_F4679660F98F144A');
        $this->addSql('DROP INDEX uniq_f4679660989d9b62 ON pollinisateurs_usergroups');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A1A7A7D3989D9B62 ON pollinisateurs_usergroups (slug)');
        $this->addSql('DROP INDEX uniq_f4679660f98f144a ON pollinisateurs_usergroups');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A1A7A7D3F98F144A ON pollinisateurs_usergroups (logo_id)');
        $this->addSql('DROP INDEX uniq_f4679660922726e9 ON pollinisateurs_usergroups');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A1A7A7D3922726E9 ON pollinisateurs_usergroups (cover_id)');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups ADD CONSTRAINT FK_F4679660922726E9 FOREIGN KEY (cover_id) REFERENCES pollinisateurs_files (id)');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups ADD CONSTRAINT FK_F4679660F98F144A FOREIGN KEY (logo_id) REFERENCES pollinisateurs_files (id)');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups_categories DROP FOREIGN KEY FK_86FA2E5B12469DE2');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups_categories DROP FOREIGN KEY FK_86FA2E5BD2112630');
        $this->addSql('DROP INDEX idx_86fa2e5bd2112630 ON pollinisateurs_usergroups_categories');
        $this->addSql('CREATE INDEX IDX_62A32135D2112630 ON pollinisateurs_usergroups_categories (usergroup_id)');
        $this->addSql('DROP INDEX idx_86fa2e5b12469de2 ON pollinisateurs_usergroups_categories');
        $this->addSql('CREATE INDEX IDX_62A3213512469DE2 ON pollinisateurs_usergroups_categories (category_id)');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups_categories ADD CONSTRAINT FK_86FA2E5B12469DE2 FOREIGN KEY (category_id) REFERENCES pollinisateurs_categories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups_categories ADD CONSTRAINT FK_86FA2E5BD2112630 FOREIGN KEY (usergroup_id) REFERENCES pollinisateurs_usergroups (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups_memberships DROP FOREIGN KEY FK_39362F08D2112630');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups_memberships DROP FOREIGN KEY FK_39362F08A76ED395');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups_memberships CHANGE notifications_settings notifications_settings LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\'');
        $this->addSql('DROP INDEX idx_39362f08a76ed395 ON pollinisateurs_usergroups_memberships');
        $this->addSql('CREATE INDEX IDX_93D83A58A76ED395 ON pollinisateurs_usergroups_memberships (user_id)');
        $this->addSql('DROP INDEX idx_39362f08d2112630 ON pollinisateurs_usergroups_memberships');
        $this->addSql('CREATE INDEX IDX_93D83A58D2112630 ON pollinisateurs_usergroups_memberships (usergroup_id)');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups_memberships ADD CONSTRAINT FK_39362F08D2112630 FOREIGN KEY (usergroup_id) REFERENCES pollinisateurs_usergroups (id)');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups_memberships ADD CONSTRAINT FK_39362F08A76ED395 FOREIGN KEY (user_id) REFERENCES pollinisateurs_users (id)');
        $this->addSql('ALTER TABLE pollinisateurs_users DROP FOREIGN KEY FK_B94B7BB86383B10');
        $this->addSql('ALTER TABLE pollinisateurs_users DROP FOREIGN KEY FK_B94B7BBF6BD1646');
        $this->addSql('ALTER TABLE pollinisateurs_users ADD favorite_environment VARCHAR(20) DEFAULT NULL, CHANGE roles roles LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\'');
        $this->addSql('DROP INDEX uniq_b94b7bbe7927c74 ON pollinisateurs_users');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F773009BE7927C74 ON pollinisateurs_users (email)');
        $this->addSql('DROP INDEX uniq_b94b7bb86383b10 ON pollinisateurs_users');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F773009B86383B10 ON pollinisateurs_users (avatar_id)');
        $this->addSql('DROP INDEX idx_b94b7bbf6bd1646 ON pollinisateurs_users');
        $this->addSql('CREATE INDEX IDX_F773009BF6BD1646 ON pollinisateurs_users (site_id)');
        $this->addSql('ALTER TABLE pollinisateurs_users ADD CONSTRAINT FK_B94B7BB86383B10 FOREIGN KEY (avatar_id) REFERENCES pollinisateurs_files (id)');
        $this->addSql('ALTER TABLE pollinisateurs_users ADD CONSTRAINT FK_B94B7BBF6BD1646 FOREIGN KEY (site_id) REFERENCES pollinisateurs_sites (id)');
        $this->addSql('ALTER TABLE pollinisateurs_users_skills DROP FOREIGN KEY FK_FA38CFB55585C142');
        $this->addSql('ALTER TABLE pollinisateurs_users_skills DROP FOREIGN KEY FK_FA38CFB5A76ED395');
        $this->addSql('DROP INDEX idx_fa38cfb5a76ed395 ON pollinisateurs_users_skills');
        $this->addSql('CREATE INDEX IDX_640E6734A76ED395 ON pollinisateurs_users_skills (user_id)');
        $this->addSql('DROP INDEX idx_fa38cfb55585c142 ON pollinisateurs_users_skills');
        $this->addSql('CREATE INDEX IDX_640E67345585C142 ON pollinisateurs_users_skills (skill_id)');
        $this->addSql('ALTER TABLE pollinisateurs_users_skills ADD CONSTRAINT FK_FA38CFB55585C142 FOREIGN KEY (skill_id) REFERENCES pollinisateurs_skills (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pollinisateurs_users_skills ADD CONSTRAINT FK_FA38CFB5A76ED395 FOREIGN KEY (user_id) REFERENCES pollinisateurs_users (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE pollinisateurs_users_skills DROP FOREIGN KEY FK_640E6734A76ED395');
        $this->addSql('ALTER TABLE pollinisateurs_users_skills DROP FOREIGN KEY FK_640E67345585C142');
        $this->addSql('DROP INDEX idx_640e67345585c142 ON pollinisateurs_users_skills');
        $this->addSql('CREATE INDEX IDX_FA38CFB55585C142 ON pollinisateurs_users_skills (skill_id)');
        $this->addSql('DROP INDEX idx_640e6734a76ed395 ON pollinisateurs_users_skills');
        $this->addSql('CREATE INDEX IDX_FA38CFB5A76ED395 ON pollinisateurs_users_skills (user_id)');
        $this->addSql('ALTER TABLE pollinisateurs_users_skills ADD CONSTRAINT FK_640E6734A76ED395 FOREIGN KEY (user_id) REFERENCES pollinisateurs_users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pollinisateurs_users_skills ADD CONSTRAINT FK_640E67345585C142 FOREIGN KEY (skill_id) REFERENCES pollinisateurs_skills (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups_memberships DROP FOREIGN KEY FK_93D83A58A76ED395');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups_memberships DROP FOREIGN KEY FK_93D83A58D2112630');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups_memberships CHANGE notifications_settings notifications_settings LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('DROP INDEX idx_93d83a58a76ed395 ON pollinisateurs_usergroups_memberships');
        $this->addSql('CREATE INDEX IDX_39362F08A76ED395 ON pollinisateurs_usergroups_memberships (user_id)');
        $this->addSql('DROP INDEX idx_93d83a58d2112630 ON pollinisateurs_usergroups_memberships');
        $this->addSql('CREATE INDEX IDX_39362F08D2112630 ON pollinisateurs_usergroups_memberships (usergroup_id)');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups_memberships ADD CONSTRAINT FK_93D83A58A76ED395 FOREIGN KEY (user_id) REFERENCES pollinisateurs_users (id)');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups_memberships ADD CONSTRAINT FK_93D83A58D2112630 FOREIGN KEY (usergroup_id) REFERENCES pollinisateurs_usergroups (id)');
        $this->addSql('ALTER TABLE pollinisateurs_document DROP FOREIGN KEY FK_E1D18C1BA76ED395');
        $this->addSql('ALTER TABLE pollinisateurs_document DROP FOREIGN KEY FK_E1D18C1BD2112630');
        $this->addSql('ALTER TABLE pollinisateurs_document DROP FOREIGN KEY FK_E1D18C1B93CB796C');
        $this->addSql('ALTER TABLE pollinisateurs_document DROP FOREIGN KEY FK_E1D18C1B162CB942');
        $this->addSql('DROP INDEX idx_e1d18c1bd2112630 ON pollinisateurs_document');
        $this->addSql('CREATE INDEX IDX_4C7685A3D2112630 ON pollinisateurs_document (usergroup_id)');
        $this->addSql('DROP INDEX idx_e1d18c1b93cb796c ON pollinisateurs_document');
        $this->addSql('CREATE INDEX IDX_4C7685A393CB796C ON pollinisateurs_document (file_id)');
        $this->addSql('DROP INDEX idx_e1d18c1b162cb942 ON pollinisateurs_document');
        $this->addSql('CREATE INDEX IDX_4C7685A3162CB942 ON pollinisateurs_document (folder_id)');
        $this->addSql('DROP INDEX idx_e1d18c1ba76ed395 ON pollinisateurs_document');
        $this->addSql('CREATE INDEX IDX_4C7685A3A76ED395 ON pollinisateurs_document (user_id)');
        $this->addSql('ALTER TABLE pollinisateurs_document ADD CONSTRAINT FK_E1D18C1BA76ED395 FOREIGN KEY (user_id) REFERENCES pollinisateurs_users (id)');
        $this->addSql('ALTER TABLE pollinisateurs_document ADD CONSTRAINT FK_E1D18C1BD2112630 FOREIGN KEY (usergroup_id) REFERENCES pollinisateurs_usergroups (id)');
        $this->addSql('ALTER TABLE pollinisateurs_document ADD CONSTRAINT FK_E1D18C1B93CB796C FOREIGN KEY (file_id) REFERENCES pollinisateurs_files (id)');
        $this->addSql('ALTER TABLE pollinisateurs_document ADD CONSTRAINT FK_E1D18C1B162CB942 FOREIGN KEY (folder_id) REFERENCES pollinisateurs_document_folder (id)');
        $this->addSql('ALTER TABLE pollinisateurs_discussion_message_file DROP FOREIGN KEY FK_EF1EEBEED1F18135');
        $this->addSql('ALTER TABLE pollinisateurs_discussion_message_file DROP FOREIGN KEY FK_EF1EEBEE93CB796C');
        $this->addSql('DROP INDEX idx_ef1eebeed1f18135 ON pollinisateurs_discussion_message_file');
        $this->addSql('CREATE INDEX IDX_84DF540FD1F18135 ON pollinisateurs_discussion_message_file (discussion_message_id)');
        $this->addSql('DROP INDEX idx_ef1eebee93cb796c ON pollinisateurs_discussion_message_file');
        $this->addSql('CREATE INDEX IDX_84DF540F93CB796C ON pollinisateurs_discussion_message_file (file_id)');
        $this->addSql('ALTER TABLE pollinisateurs_discussion_message_file ADD CONSTRAINT FK_EF1EEBEED1F18135 FOREIGN KEY (discussion_message_id) REFERENCES pollinisateurs_discussion_message (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pollinisateurs_discussion_message_file ADD CONSTRAINT FK_EF1EEBEE93CB796C FOREIGN KEY (file_id) REFERENCES pollinisateurs_files (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pollinisateurs_pages_revisions DROP FOREIGN KEY FK_D2E795D0C4663E4');
        $this->addSql('ALTER TABLE pollinisateurs_pages_revisions DROP FOREIGN KEY FK_D2E795D0A76ED395');
        $this->addSql('ALTER TABLE pollinisateurs_pages_revisions CHANGE data data LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('DROP INDEX idx_d2e795d0c4663e4 ON pollinisateurs_pages_revisions');
        $this->addSql('CREATE INDEX IDX_9B744781C4663E4 ON pollinisateurs_pages_revisions (page_id)');
        $this->addSql('DROP INDEX idx_d2e795d0a76ed395 ON pollinisateurs_pages_revisions');
        $this->addSql('CREATE INDEX IDX_9B744781A76ED395 ON pollinisateurs_pages_revisions (user_id)');
        $this->addSql('ALTER TABLE pollinisateurs_pages_revisions ADD CONSTRAINT FK_D2E795D0C4663E4 FOREIGN KEY (page_id) REFERENCES pollinisateurs_pages (id)');
        $this->addSql('ALTER TABLE pollinisateurs_pages_revisions ADD CONSTRAINT FK_D2E795D0A76ED395 FOREIGN KEY (user_id) REFERENCES pollinisateurs_users (id)');
        $this->addSql('ALTER TABLE pollinisateurs_discussion DROP FOREIGN KEY FK_F9897068D2112630');
        $this->addSql('ALTER TABLE pollinisateurs_discussion DROP FOREIGN KEY FK_F9897068F675F31B');
        $this->addSql('DROP INDEX idx_f9897068d2112630 ON pollinisateurs_discussion');
        $this->addSql('CREATE INDEX IDX_AC4941DBD2112630 ON pollinisateurs_discussion (usergroup_id)');
        $this->addSql('DROP INDEX idx_f9897068f675f31b ON pollinisateurs_discussion');
        $this->addSql('CREATE INDEX IDX_AC4941DBF675F31B ON pollinisateurs_discussion (author_id)');
        $this->addSql('ALTER TABLE pollinisateurs_discussion ADD CONSTRAINT FK_F9897068D2112630 FOREIGN KEY (usergroup_id) REFERENCES pollinisateurs_usergroups (id)');
        $this->addSql('ALTER TABLE pollinisateurs_discussion ADD CONSTRAINT FK_F9897068F675F31B FOREIGN KEY (author_id) REFERENCES pollinisateurs_users (id)');
        $this->addSql('ALTER TABLE pollinisateurs_files DROP FOREIGN KEY FK_E5C5E52BA76ED395');
        $this->addSql('ALTER TABLE pollinisateurs_files DROP FOREIGN KEY FK_E5C5E52BD2112630');
        $this->addSql('DROP INDEX idx_e5c5e52ba76ed395 ON pollinisateurs_files');
        $this->addSql('CREATE INDEX IDX_1922520BA76ED395 ON pollinisateurs_files (user_id)');
        $this->addSql('DROP INDEX idx_e5c5e52bd2112630 ON pollinisateurs_files');
        $this->addSql('CREATE INDEX IDX_1922520BD2112630 ON pollinisateurs_files (usergroup_id)');
        $this->addSql('ALTER TABLE pollinisateurs_files ADD CONSTRAINT FK_E5C5E52BA76ED395 FOREIGN KEY (user_id) REFERENCES pollinisateurs_users (id)');
        $this->addSql('ALTER TABLE pollinisateurs_files ADD CONSTRAINT FK_E5C5E52BD2112630 FOREIGN KEY (usergroup_id) REFERENCES pollinisateurs_usergroups (id)');
        $this->addSql('ALTER TABLE pollinisateurs_articles DROP FOREIGN KEY FK_86653705D2112630');
        $this->addSql('ALTER TABLE pollinisateurs_articles DROP FOREIGN KEY FK_86653705F675F31B');
        $this->addSql('ALTER TABLE pollinisateurs_articles DROP FOREIGN KEY FK_86653705922726E9');
        $this->addSql('DROP INDEX uniq_86653705922726e9 ON pollinisateurs_articles');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2BC23EBD922726E9 ON pollinisateurs_articles (cover_id)');
        $this->addSql('DROP INDEX idx_86653705d2112630 ON pollinisateurs_articles');
        $this->addSql('CREATE INDEX IDX_2BC23EBDD2112630 ON pollinisateurs_articles (usergroup_id)');
        $this->addSql('DROP INDEX idx_86653705f675f31b ON pollinisateurs_articles');
        $this->addSql('CREATE INDEX IDX_2BC23EBDF675F31B ON pollinisateurs_articles (author_id)');
        $this->addSql('ALTER TABLE pollinisateurs_articles ADD CONSTRAINT FK_86653705D2112630 FOREIGN KEY (usergroup_id) REFERENCES pollinisateurs_usergroups (id)');
        $this->addSql('ALTER TABLE pollinisateurs_articles ADD CONSTRAINT FK_86653705F675F31B FOREIGN KEY (author_id) REFERENCES pollinisateurs_users (id)');
        $this->addSql('ALTER TABLE pollinisateurs_articles ADD CONSTRAINT FK_86653705922726E9 FOREIGN KEY (cover_id) REFERENCES pollinisateurs_files (id)');
        $this->addSql('ALTER TABLE pollinisateurs_log_events DROP FOREIGN KEY FK_7F4D8D8FA76ED395');
        $this->addSql('ALTER TABLE pollinisateurs_log_events DROP FOREIGN KEY FK_7F4D8D8FD2112630');
        $this->addSql('ALTER TABLE pollinisateurs_log_events CHANGE data data LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('DROP INDEX idx_7f4d8d8fd2112630 ON pollinisateurs_log_events');
        $this->addSql('CREATE INDEX IDX_2A8DBC3CD2112630 ON pollinisateurs_log_events (usergroup_id)');
        $this->addSql('DROP INDEX idx_7f4d8d8fa76ed395 ON pollinisateurs_log_events');
        $this->addSql('CREATE INDEX IDX_2A8DBC3CA76ED395 ON pollinisateurs_log_events (user_id)');
        $this->addSql('ALTER TABLE pollinisateurs_log_events ADD CONSTRAINT FK_7F4D8D8FA76ED395 FOREIGN KEY (user_id) REFERENCES pollinisateurs_users (id)');
        $this->addSql('ALTER TABLE pollinisateurs_log_events ADD CONSTRAINT FK_7F4D8D8FD2112630 FOREIGN KEY (usergroup_id) REFERENCES pollinisateurs_usergroups (id)');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups DROP FOREIGN KEY FK_A1A7A7D3F98F144A');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups DROP FOREIGN KEY FK_A1A7A7D3922726E9');
        $this->addSql('DROP INDEX uniq_a1a7a7d3989d9b62 ON pollinisateurs_usergroups');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F4679660989D9B62 ON pollinisateurs_usergroups (slug)');
        $this->addSql('DROP INDEX uniq_a1a7a7d3f98f144a ON pollinisateurs_usergroups');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F4679660F98F144A ON pollinisateurs_usergroups (logo_id)');
        $this->addSql('DROP INDEX uniq_a1a7a7d3922726e9 ON pollinisateurs_usergroups');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F4679660922726E9 ON pollinisateurs_usergroups (cover_id)');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups ADD CONSTRAINT FK_A1A7A7D3F98F144A FOREIGN KEY (logo_id) REFERENCES pollinisateurs_files (id)');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups ADD CONSTRAINT FK_A1A7A7D3922726E9 FOREIGN KEY (cover_id) REFERENCES pollinisateurs_files (id)');
        $this->addSql('ALTER TABLE pollinisateurs_document_folder DROP FOREIGN KEY FK_C36C826DD2112630');
        $this->addSql('DROP INDEX idx_c36c826dd2112630 ON pollinisateurs_document_folder');
        $this->addSql('CREATE INDEX IDX_8AFF503CD2112630 ON pollinisateurs_document_folder (usergroup_id)');
        $this->addSql('ALTER TABLE pollinisateurs_document_folder ADD CONSTRAINT FK_C36C826DD2112630 FOREIGN KEY (usergroup_id) REFERENCES pollinisateurs_usergroups (id)');
        $this->addSql('DROP INDEX uniq_6bd9f6c5989d9b62 ON pollinisateurs_skills');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_504B31BA989D9B62 ON pollinisateurs_skills (slug)');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups_categories DROP FOREIGN KEY FK_62A32135D2112630');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups_categories DROP FOREIGN KEY FK_62A3213512469DE2');
        $this->addSql('DROP INDEX idx_62a32135d2112630 ON pollinisateurs_usergroups_categories');
        $this->addSql('CREATE INDEX IDX_86FA2E5BD2112630 ON pollinisateurs_usergroups_categories (usergroup_id)');
        $this->addSql('DROP INDEX idx_62a3213512469de2 ON pollinisateurs_usergroups_categories');
        $this->addSql('CREATE INDEX IDX_86FA2E5B12469DE2 ON pollinisateurs_usergroups_categories (category_id)');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups_categories ADD CONSTRAINT FK_62A32135D2112630 FOREIGN KEY (usergroup_id) REFERENCES pollinisateurs_usergroups (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pollinisateurs_usergroups_categories ADD CONSTRAINT FK_62A3213512469DE2 FOREIGN KEY (category_id) REFERENCES pollinisateurs_categories (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX uniq_5ff00f115e237e06 ON pollinisateurs_sites');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A317B8315E237E06 ON pollinisateurs_sites (name)');
        $this->addSql('ALTER TABLE pollinisateurs_users DROP FOREIGN KEY FK_F773009B86383B10');
        $this->addSql('ALTER TABLE pollinisateurs_users DROP FOREIGN KEY FK_F773009BF6BD1646');
        $this->addSql('ALTER TABLE pollinisateurs_users DROP favorite_environment, CHANGE roles roles LONGTEXT NOT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('DROP INDEX uniq_f773009be7927c74 ON pollinisateurs_users');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B94B7BBE7927C74 ON pollinisateurs_users (email)');
        $this->addSql('DROP INDEX uniq_f773009b86383b10 ON pollinisateurs_users');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B94B7BB86383B10 ON pollinisateurs_users (avatar_id)');
        $this->addSql('DROP INDEX idx_f773009bf6bd1646 ON pollinisateurs_users');
        $this->addSql('CREATE INDEX IDX_B94B7BBF6BD1646 ON pollinisateurs_users (site_id)');
        $this->addSql('ALTER TABLE pollinisateurs_users ADD CONSTRAINT FK_F773009B86383B10 FOREIGN KEY (avatar_id) REFERENCES pollinisateurs_files (id)');
        $this->addSql('ALTER TABLE pollinisateurs_users ADD CONSTRAINT FK_F773009BF6BD1646 FOREIGN KEY (site_id) REFERENCES pollinisateurs_sites (id)');
        $this->addSql('ALTER TABLE pollinisateurs_pages DROP FOREIGN KEY FK_C3844007D2112630');
        $this->addSql('ALTER TABLE pollinisateurs_pages DROP FOREIGN KEY FK_C3844007F675F31B');
        $this->addSql('ALTER TABLE pollinisateurs_pages DROP FOREIGN KEY FK_C3844007922726E9');
        $this->addSql('DROP INDEX idx_c3844007f675f31b ON pollinisateurs_pages');
        $this->addSql('CREATE INDEX IDX_3F63F727F675F31B ON pollinisateurs_pages (author_id)');
        $this->addSql('DROP INDEX uniq_c3844007922726e9 ON pollinisateurs_pages');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3F63F727922726E9 ON pollinisateurs_pages (cover_id)');
        $this->addSql('DROP INDEX idx_c3844007d2112630 ON pollinisateurs_pages');
        $this->addSql('CREATE INDEX IDX_3F63F727D2112630 ON pollinisateurs_pages (usergroup_id)');
        $this->addSql('ALTER TABLE pollinisateurs_pages ADD CONSTRAINT FK_C3844007D2112630 FOREIGN KEY (usergroup_id) REFERENCES pollinisateurs_usergroups (id)');
        $this->addSql('ALTER TABLE pollinisateurs_pages ADD CONSTRAINT FK_C3844007F675F31B FOREIGN KEY (author_id) REFERENCES pollinisateurs_users (id)');
        $this->addSql('ALTER TABLE pollinisateurs_pages ADD CONSTRAINT FK_C3844007922726E9 FOREIGN KEY (cover_id) REFERENCES pollinisateurs_files (id)');
        $this->addSql('ALTER TABLE pollinisateurs_discussion_message DROP FOREIGN KEY FK_5108CD1B1ADED311');
        $this->addSql('ALTER TABLE pollinisateurs_discussion_message DROP FOREIGN KEY FK_5108CD1BF675F31B');
        $this->addSql('DROP INDEX idx_5108cd1bf675f31b ON pollinisateurs_discussion_message');
        $this->addSql('CREATE INDEX IDX_E67EECB6F675F31B ON pollinisateurs_discussion_message (author_id)');
        $this->addSql('DROP INDEX idx_5108cd1b1aded311 ON pollinisateurs_discussion_message');
        $this->addSql('CREATE INDEX IDX_E67EECB61ADED311 ON pollinisateurs_discussion_message (discussion_id)');
        $this->addSql('ALTER TABLE pollinisateurs_discussion_message ADD CONSTRAINT FK_5108CD1B1ADED311 FOREIGN KEY (discussion_id) REFERENCES pollinisateurs_discussion (id)');
        $this->addSql('ALTER TABLE pollinisateurs_discussion_message ADD CONSTRAINT FK_5108CD1BF675F31B FOREIGN KEY (author_id) REFERENCES pollinisateurs_users (id)');
    }
}
