platform:
    logo:
        fileId: 'naturadapt_logo_116x60.png'
home:
    front:
        fileId: 'front-hero.jpg'
    sur_titre: Bienvenue sur Natur’Adapt
    texte_principal: Adapter la protection de la nature aux défis du changement climatique en Europe.
    premier_texte:  |
        <h2>Bienvenue sur la communauté Natur’Adapt !</h2>
        <p><strong>De quoi parle-t-on ?</strong> La communauté Natur’Adapt s’intéresse au changement climatique et à ses impacts sur la nature, notamment dans les espaces naturels protégés (réserves naturelles, sites natura 2000, parcs nationaux, parcs naturels régionaux,…).
        </p>
            <p>La montée du niveau marin en bord de mer, la hausse des températures, la diminution de l’enneigement, ou encore des événements extrêmes plus fréquents et plus intenses ont des effets sur la faune et la flore : remontée des espèces vers le Nord/en altitude ; décalage des migrations saisonnières et des périodes de végétation ; apparition de nouvelles maladies, de nouveaux parasites ou d’espèces exotiques envahissantes ; modification des interactions entre espèces; mortalités; etc.
            </p>
            <p>Alors, comment adapter la gestion de ces espaces de nature face au changement climatique et à ses impacts? C’est tout l’objet de cette communauté !
            </p>
            <h2>Pourquoi cette communauté ?</h2>
        <p>Le changement climatique est un sujet qui peut parfois être difficile à appréhender. Les professionnels des espaces naturels, qui observent déjà les conséquences du changement climatique, ont besoin d’être accompagnés pour mettre en place des solutions. Les outils techniques (guides, formations, etc.) sont indispensables mais ne suffisent pas : la communauté Natur’Adapt permet d’avancer collectivement grâce à l’échange d’actualités, d’informations, de retours d’expérience mais aussi de questionnements !
            </p>
        <p>Développée dans le cadre du <a href="/groups/communaute/pages/a-propos-du-projet-natur-adapt">projet LIFE Natur’Adapt</a>,la communauté est notamment animée grâce à la plateforme collaborative naturadapt.com sur laquelle vous êtes, et qui a vocation à perdurer après le projet. Elle regroupe toutes les personnes intéressées et sensibilisées aux enjeux du changement climatique et de la protection de la nature : gestionnaires d’espaces naturels protégés, scientifiques, animateurs, naturalistes, élus, citoyens, étudiants, débutants ou experts du climat, simplement curieux ou amoureux de la nature.
            </p>
        <p>En résumé, la communauté Natur'Adapt, c'est <strong>un groupe passionné, multi-acteurs et évolutif, qui échange connaissances et retours d’expériences de manière conviviale autour d’une problématique commune : l’adaptation au changement climatique dans les aires protégées</strong>.
            </p>
        <p>Nos valeurs communes et principes de fonctionnement sont inscrits dans < a href="/groups/communaute/pages/charte-de-la-plateforme">une charte que nous vous invitons à lire</a>.
            </p>
            <p>Intéressés par l’aventure ? <a href="/groups/communaute/pages/a-propos-de-la-communaute-natur-adapt">Rejoignez la communauté Natur’Adapt ici ! C’est gratuit, libre et réversible !></a>
            </p>  
        <h2>Que pouvez-vous y trouver ?</h2>


        <figure class="image threeImagesInSameLine">
        <img src="/media/layout/contacts_et_membres.svg" alt="">
        </figure>
        <p><a href="/groups/communaute/pages/a-propos-de-la-communaute-natur-adapt">Les contacts des membres de la communauté, via </a><a href="/members">l’annuaire</a></p>
        <figure class="image threeImagesInSameLine">
        <img src="/media/layout/listes_discussions.svg" alt="">
        </figure>
        <p>Des listes de discussion pour échanger</p>
        <figure class="image threeImagesInSameLine">
        <img src="/media/layout/ressources_prod.svg" alt="">
        </figure>
        <p>Des ressources et des productions collaboratives</p><p>&nbsp;</p>
          
        <p>Cette plateforme est constituée de <a href="/groups/communaute/pages/a-propos-de-la-communaute-natur-adapt">« groupes »</a> dédiés à un sujet lié au changement climatique et aux espaces naturels.<br />
        Vous pourrez rejoindre les groupes que vous souhaitez selon vos intérêts, puis échanger, partager vos idées, une actualité, un document, etc. avec les autres membres du groupe. Certains groupes sont ouverts, sans modération pour y entrer. D’autres sont privés (indiqués par un symbole cadenas) : un animateur validera ou non votre demande.
        </p>
            <p>Le groupe « Communauté » rassemble l’intégralité des membres de la plateforme, ainsi que les documents, pages et actualités qui peuvent intéresser tous les inscrits.
            </p>
            <p>La plateforme est collaborative, ce qui signifie que vous êtes libre de créer du contenu ou de réagir, sans modération ou presque. Vous pouvez même à votre tour <a href="/groups/new">créer un groupe si vous le souhaitez !</a></p>
        <ul>
        <li><a href="/groups/communaute/pages/tutoriels-d-utilisation-de-la-plateforme>Prise en main de la plateforme et de ses fonctionnalités.</li>
        </ul>
        <p><strong>Découvrir et comprendre <a href="/groups/communaute/pages/a-propos-du-projet-natur-adapt">le projet LIFE Natur’Adapt en quelques mots et en vidéo</a></strong>.
            </p>


    premier_clique_visibility: true
    premier_clique_texte: Suivez les actualités
    premier_clique_bouton_texte: S'abonner à la newsletter
    premier_clique_lien: /groups/communaute/pages/newsletter


    second_texte: |
        <figure class="image reducedSize20"><img src="/media/layout/help.svg" alt=""></figure>
        <div>
        <h2>Comment s'inscrire ?</h2>
        <ul>
        <li>1. RDV en haut à droite puis cliquez sur le bouton vert « Connexion »</li>
        <li>2. Tapez votre adresse mail et choisissez un mot de passe</li>
        <li>3. Ouvrez le mail de confirmation d’inscription reçu sur votre boite mail</li>
        </ul>
        <p>Bienvenue en tant que <strong>Natur’Acteur, Natur’Actrice</strong> de notre communauté ! Vous pouvez par ailleurs, vous <a href="/groups/communaute/pages/newsletter">inscrire à la newsletter du LIFE Natur’Adapt pour suivre les actualités du projet</a>.</p>
        </div>

    second_clique_visibility: true
    second_clique_texte: Vous avez suivi le MOOC Natur’Adapt ?
    second_clique_bouton_texte: Rejoignez le groupe dédié juste ici pour continuer vos échanges !
    second_clique_lien:  /groups/moocoeurs
    troisieme_texte: |
        <ul>
        <li>Contacter le support de la plateforme : <a href="mailto:support@naturadapt.com">support@naturadapt.com</a></li>
        <li>Contacter l’équipe du projet : <a href="mailto:naturadapt-rnf@espaces-naturels.fr">naturadapt-rnf@espaces-naturels.fr</a></li>
        </ul>
groups:
    frontgroup:
        fileId: 'groups-hero.jpg'

menus:
    navbarLiens:
        title:
        liens:
        -
            nom: 'À propos de la plateforme'
            lien: '/'
        -
            nom: Groupes
            lien: '/groups/'
        -
            nom: Ressources
            lien: '/groups/communaute/pages/ressources/'
        -
            nom: Actualités
            lien: '/groups/communaute/articles/'
        -
            nom: Annuaire
            lien: '/members'
    footbarFirstLiens:
        title: 'Menu'
        liens:
        -
            nom: Accueil
            lien: '/'
        -
            nom: 'Connexion / Inscription'
            lien: '/login/'
        -
            nom: Groupes
            lien: '/groups/'
        -
            nom: Annuaire
            lien: '/members/'
        -
            nom: Ressources
            lien: '/groups/communaute/pages/ressources/'
    footbarSecondLiens:
        title: 'En savoir plus'
        liens:
        -
            nom: 'À propos du projet Natur’Adapt'
            lien: '/groups/communaute/pages/a-propos-du-projet-natur-adapt'
        -
            nom: Newsletter
            lien: '/communaute/pages/newsletter'
        -
            nom: 'À propos de la plateforme'
            lien: '/groups/communaute/pages/a-propos-de-la-plateforme'
        -
            nom: 'Charte de la plateforme'
            lien: '/groups/communaute/pages/charte-de-la-plateforme'
        -
            nom: 'Mentions Légales'
            lien: '/groups/plateforme-web/pages/mentions-legales'
    footbarThirdLiens:
        title: 'Aide'
        liens:
        -
            nom: 'Tutoriels d’utilisation de la plateforme'
            lien: '/groups/communaute/tutoriels-d-utilisation-de-la-plateforme'
        -
            nom: 'Règles d’utilisation de la plateforme'
            lien: '/groups/plateforme-web/pages/regles'
        -
            nom: 'Signaler un problème'
            lien: 'mailto:support@naturadapt.com'


