name: PHP Composer

on:
  push:
    branches: [ develop, github-actions ]
  pull_request:
    branches: [ develop, github-actions ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      APP_ENV: test
      APP_SECRET: 0116ea354117af2c822bb1aeb5d7d367
      DATABASE_URL: mysql://root:@127.0.0.1:3306/circle_test
      DATABASE_PREFIX: naturadapt_
      SYMFONY_DEPRECATIONS_HELPER: weak

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Run database migrations
      run: php bin/console doctrine:migrations:migrate --no-interaction
      
    - name: Load database fixtures
      run: php bin/console doctrine:fixtures:load --no-interaction
      
    - name: Warm up cache
      run: php bin/console cache:clear
            
    - name: Run webpack
      run: npm run build

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: ./bin/phpunit
